package rocks.bastion.core;

import org.apache.http.entity.ContentType;

import java.util.Collection;
import java.util.LinkedList;

/**
 * @author <a href="mailto:mail@kylepullicino.com">Kyle</a>
 */
public class GeneralRequest extends AbstractRequest {

    private GeneralRequest(HttpMethod method, String url, String body) {
        super(method, url, body);

        this.name = method.getValue() + " " + url;
        this.contentType = ContentType.TEXT_PLAIN;
        this.headers = new LinkedList<>();
        this.queryParams = new LinkedList<>();
    }

    /**
     * Construct an HTTP request, using the GET method, to be sent on the specified URL. It will also have
     * a descriptive name which is generated by combining the HTTP method with the URL. Use the {@link GeneralRequest#addQueryParam(String, String)}
     * to add query parameters to the request.
     *
     * @param url A non-{@literal null} URL to send the request on
     * @return An HTTP request using the get method
     */
    public static GeneralRequest get(String url) {
        return new GeneralRequest(HttpMethod.GET, url, null);
    }

    /**
     * Construct an HTTP request, using the POST method, to be sent on the specified URL and with the specified content body.
     * The request will initially be sent with a content-type of "text/plain". It will also have a descriptive name which
     * is generated by combining the HTTP method with the URL. If you would like to send some other representation of content
     * body then we suggest using some other implementation of {@link Request}.
     *
     * @param url A non-{@literal null} URL to send the request on
     * @return An HTTP request using the get method
     */
    public static GeneralRequest post(String url, String body) {
        return new GeneralRequest(HttpMethod.POST, url, body);
    }

    /**
     * Construct an HTTP request, using the DELETE method, to be sent on the specified URL and with the specified content body.
     * The request will initially be sent with a content-type of "text/plain". It will also have a descriptive name which
     * is generated by combining the HTTP method with the URL. If you would like to send some other representation of content
     * body then we suggest using some other implementation of {@link Request}.
     *
     * @param url A non-{@literal null} URL to send the request on
     * @return An HTTP request using the get method
     */
    public static GeneralRequest delete(String url, String body) {
        return new GeneralRequest(HttpMethod.DELETE, url, body);
    }

    /**
     * Construct an HTTP request, using the PUT method, to be sent on the specified URL and with the specified content body.
     * The request will initially be sent with a content-type of "text/plain". It will also have a descriptive name which
     * is generated by combining the HTTP method with the URL. If you would like to send some other representation of content
     * body then we suggest using some other implementation of {@link Request}.
     *
     * @param url A non-{@literal null} URL to send the request on
     * @return An HTTP request using the get method
     */
    public static GeneralRequest put(String url, String body) {
        return new GeneralRequest(HttpMethod.PUT, url, body);
    }

    /**
     * Construct an HTTP request, using the PUT method, to be sent on the specified URL and with the specified content body.
     * The request will initially be sent with a content-type of "text/plain". It will also have a descriptive name which
     * is generated by combining the HTTP method with the URL. If you would like to send some other representation of content
     * body then we suggest using some other implementation of {@link Request}.
     *
     * @param url A non-{@literal null} URL to send the request on
     * @return An HTTP request using the get method
     */
    public static GeneralRequest patch(String url, String body) {
        return new GeneralRequest(HttpMethod.PATCH, url, body);
    }

    @Override
    public String name() {
        return name;
    }

    @Override
    public String url() {
        return url;
    }

    @Override
    public HttpMethod method() {
        return method;
    }

    @Override
    public ContentType contentType() {
        return contentType;
    }

    @Override
    public Collection<ApiHeader> headers() {
        return headers;
    }

    @Override
    public Collection<ApiQueryParam> queryParams() {
        return queryParams;
    }

    @Override
    public Object body() {
        return body;
    }
}
